/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Start Here',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Chapter 1: Sciila',
      items: [
        'scilla/intro',
        'scilla/maps',
        'scilla/events_errors'
      ],
    },
    {
      type: 'category',
      label: 'ZilliqaJS',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'React DApp Development',
      items: ['intro'],
    },
  ],
};

module.exports = sidebars;
